load("@kanna_cli_crates//:defs.bzl", all_crate_deps_for_cli = "all_crate_deps")
load("@kanna_mcp_crates//:defs.bzl", all_crate_deps_for_mcp = "all_crate_deps")
load("@kanna_server_crates//:defs.bzl", all_crate_deps_for_server = "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_library")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "cargo_srcs",
    srcs = [
        "Cargo.toml",
    ] + glob(["src/**"]),
)

rust_library(
    name = "kanna_tool_catalog_for_cli",
    srcs = glob(["src/**/*.rs"]),
    compile_data = ["src/catalog.json"],
    crate_root = "src/lib.rs",
    crate_name = "kanna_tool_catalog",
    edition = "2021",
    deps = all_crate_deps_for_cli(normal = True, package_name = "crates/kanna-tool-catalog") + [
        "//crates/runtime-defaults:kanna_runtime_defaults",
    ],
    proc_macro_deps = all_crate_deps_for_cli(proc_macro = True, package_name = "crates/kanna-tool-catalog"),
)

rust_library(
    name = "kanna_tool_catalog_for_mcp",
    srcs = glob(["src/**/*.rs"]),
    compile_data = ["src/catalog.json"],
    crate_root = "src/lib.rs",
    crate_name = "kanna_tool_catalog",
    edition = "2021",
    deps = all_crate_deps_for_mcp(normal = True, package_name = "crates/kanna-tool-catalog") + [
        "//crates/runtime-defaults:kanna_runtime_defaults",
    ],
    proc_macro_deps = all_crate_deps_for_mcp(proc_macro = True, package_name = "crates/kanna-tool-catalog"),
)

rust_library(
    name = "kanna_tool_catalog_for_server",
    srcs = glob(["src/**/*.rs"]),
    compile_data = ["src/catalog.json"],
    crate_root = "src/lib.rs",
    crate_name = "kanna_tool_catalog",
    edition = "2021",
    deps = all_crate_deps_for_server(normal = True, package_name = "crates/kanna-tool-catalog") + [
        "//crates/runtime-defaults:kanna_runtime_defaults",
    ],
    proc_macro_deps = all_crate_deps_for_server(proc_macro = True, package_name = "crates/kanna-tool-catalog"),
)
