// The Kanna secure channel (KSC) framing over the Noise IK core — the
// TypeScript twin of `crates/kanna-secure-channel/src/lib.rs`. The two must
// agree byte for byte; `tests/secure-channel-vectors/ksc-cross-language.json`
// (generated by the Rust crate) is what proves they do.
//
// Wire text: `ksc1:` + standard base64 of one or more length-prefixed
// (u16 big-endian) Noise messages. Transport plaintexts begin with a kind
// byte: 1 = data chunk, more follow; 2 = final data chunk; 3 = authenticated
// close (payload is a UTF-8 reason).

import { sha256 } from "@noble/hashes/sha2.js";
import {
  bytesEqual,
  concatBytes,
  decodeBase64,
  decodeBase64Url,
  encodeBase64,
  encodeBase64Url,
  utf8Decode,
  utf8Encode,
  writeUint16BE,
} from "./bytes";
import {
  CipherState,
  DHLEN,
  HandshakeState,
  MAX_NOISE_MESSAGE_LEN,
  TAGLEN,
  generateKeypair,
  keypairFromPrivate,
  type Keypair,
  type RandomBytes,
} from "./noise";

export const PROTOCOL_VERSION = 1;
export const WIRE_PREFIX = "ksc1:";
const PROLOGUE_PREFIX = utf8Encode("kanna-ksc/1\0");
const SAS_DOMAIN = utf8Encode("kanna-ksc/sas/1\0");
const CHUNK_KIND_LEN = 1;
export const MAX_CHUNK_PAYLOAD_LEN = MAX_NOISE_MESSAGE_LEN - TAGLEN - CHUNK_KIND_LEN;
export const DEFAULT_MAX_MESSAGE_LEN = 128 * 1024 * 1024;
const MAX_HELLO_LEN = 4096;
const CLOSE_REASON_MAX_LEN = 1024;

const KIND_DATA_MORE = 1;
const KIND_DATA_FINAL = 2;
const KIND_CLOSE = 3;

export type { Keypair, RandomBytes };
export { generateKeypair, keypairFromPrivate };

export type SecureChannelFailure =
  | "noise"
  | "wire"
  | "hello"
  | "message_too_large"
  | "closed"
  | "nonce_exhausted"
  | "invalid_key";

export class SecureChannelError extends Error {
  constructor(
    public readonly reason: SecureChannelFailure,
    message: string,
  ) {
    super(message);
    this.name = "SecureChannelError";
  }
}

export type HelloIntent = "session" | "pairing";

export interface InitiatorHello {
  version: number;
  intent: HelloIntent;
  deviceId?: string;
  capabilities?: string[];
}

export interface ResponderHello {
  version: number;
  desktopId: string;
  capabilities?: string[];
}

export function encodeKey(key: Uint8Array): string {
  if (key.length !== DHLEN) throw new SecureChannelError("invalid_key", "key must be 32 bytes");
  return encodeBase64Url(key);
}

export function decodeKey(encoded: string): Uint8Array {
  let bytes: Uint8Array;
  try {
    bytes = decodeBase64Url(encoded.trim());
  } catch {
    throw new SecureChannelError("invalid_key", "key must be base64url");
  }
  if (bytes.length !== DHLEN) throw new SecureChannelError("invalid_key", "key must be 32 bytes");
  return bytes;
}

export function isWireFrame(text: string): boolean {
  return text.startsWith(WIRE_PREFIX);
}

function prologue(desktopId: string): Uint8Array {
  return concatBytes(PROLOGUE_PREFIX, utf8Encode(desktopId));
}

function encodeWire(records: readonly Uint8Array[]): string {
  const parts: Uint8Array[] = [];
  for (const record of records) {
    parts.push(writeUint16BE(record.length), record);
  }
  return WIRE_PREFIX + encodeBase64(concatBytes(...parts));
}

function decodeWire(text: string): Uint8Array[] {
  if (!text.startsWith(WIRE_PREFIX)) throw new SecureChannelError("wire", "missing ksc1 prefix");
  let bytes: Uint8Array;
  try {
    bytes = decodeBase64(text.slice(WIRE_PREFIX.length));
  } catch {
    throw new SecureChannelError("wire", "frame is not base64");
  }
  const records: Uint8Array[] = [];
  let offset = 0;
  while (offset < bytes.length) {
    if (offset + 2 > bytes.length) throw new SecureChannelError("wire", "truncated record length");
    const length = (bytes[offset] << 8) | bytes[offset + 1];
    offset += 2;
    if (offset + length > bytes.length) throw new SecureChannelError("wire", "truncated record");
    if (length < TAGLEN) throw new SecureChannelError("wire", "record shorter than an AEAD tag");
    records.push(bytes.slice(offset, offset + length));
    offset += length;
  }
  if (records.length === 0) throw new SecureChannelError("wire", "frame carries no records");
  return records;
}

/** Six-digit short authentication string from the handshake hash. Must match
 * `kanna_secure_channel::sas_code`. */
export function sasCode(handshakeHash: Uint8Array): string {
  const digest = sha256(concatBytes(SAS_DOMAIN, handshakeHash));
  const value =
    (((digest[0] << 24) >>> 0) + (digest[1] << 16) + (digest[2] << 8) + digest[3]) % 1_000_000;
  return String(value).padStart(6, "0");
}

function encodeHello(hello: InitiatorHello | ResponderHello): Uint8Array {
  // Field order matches the Rust serde derive so the vectors agree byte for
  // byte; the receiver parses generically, so order is not a protocol rule.
  const ordered: Record<string, unknown> = {};
  if ("intent" in hello) {
    ordered.version = hello.version;
    ordered.intent = hello.intent;
    if (hello.deviceId !== undefined) ordered.deviceId = hello.deviceId;
    if (hello.capabilities && hello.capabilities.length > 0) ordered.capabilities = hello.capabilities;
  } else {
    ordered.version = hello.version;
    ordered.desktopId = hello.desktopId;
    if (hello.capabilities && hello.capabilities.length > 0) ordered.capabilities = hello.capabilities;
  }
  const bytes = utf8Encode(JSON.stringify(ordered));
  if (bytes.length > MAX_HELLO_LEN) throw new SecureChannelError("hello", "too large");
  return bytes;
}

function parseInitiatorHello(payload: Uint8Array): InitiatorHello {
  if (payload.length > MAX_HELLO_LEN) throw new SecureChannelError("hello", "too large");
  let parsed: unknown;
  try {
    parsed = JSON.parse(utf8Decode(payload));
  } catch {
    throw new SecureChannelError("hello", "malformed initiator hello");
  }
  if (!parsed || typeof parsed !== "object") throw new SecureChannelError("hello", "malformed initiator hello");
  const record = parsed as Record<string, unknown>;
  if (record.version !== PROTOCOL_VERSION) throw new SecureChannelError("hello", "unsupported initiator version");
  if (record.intent !== "session" && record.intent !== "pairing") {
    throw new SecureChannelError("hello", "malformed initiator hello");
  }
  const deviceId = record.deviceId;
  if (deviceId !== undefined && (typeof deviceId !== "string" || !deviceId.trim() || deviceId.length > 256)) {
    throw new SecureChannelError("hello", "invalid device id");
  }
  const capabilities = Array.isArray(record.capabilities)
    ? record.capabilities.filter((value): value is string => typeof value === "string")
    : [];
  return {
    version: PROTOCOL_VERSION,
    intent: record.intent,
    ...(typeof deviceId === "string" ? { deviceId } : {}),
    capabilities,
  };
}

function parseResponderHello(payload: Uint8Array): ResponderHello {
  if (payload.length > MAX_HELLO_LEN) throw new SecureChannelError("hello", "too large");
  let parsed: unknown;
  try {
    parsed = JSON.parse(utf8Decode(payload));
  } catch {
    throw new SecureChannelError("hello", "malformed responder hello");
  }
  if (!parsed || typeof parsed !== "object") throw new SecureChannelError("hello", "malformed responder hello");
  const record = parsed as Record<string, unknown>;
  if (record.version !== PROTOCOL_VERSION) throw new SecureChannelError("hello", "unsupported responder version");
  if (typeof record.desktopId !== "string") throw new SecureChannelError("hello", "malformed responder hello");
  const capabilities = Array.isArray(record.capabilities)
    ? record.capabilities.filter((value): value is string => typeof value === "string")
    : [];
  return { version: PROTOCOL_VERSION, desktopId: record.desktopId, capabilities };
}

function noiseError(error: unknown): SecureChannelError {
  if (error instanceof SecureChannelError) return error;
  return new SecureChannelError("noise", error instanceof Error ? error.message : String(error));
}

export interface ChannelOptions {
  randomBytes: RandomBytes;
  maxMessageLen?: number;
  /** Deterministic ephemeral for test vectors only. */
  fixedEphemeral?: Uint8Array;
}

export type Received =
  | { kind: "message"; data: Uint8Array }
  | { kind: "closed"; reason: string };

export class ChannelSender {
  private nonce = 0n;
  private closed = false;

  constructor(private readonly cipher: CipherState) {}

  private sealRecord(kind: number, payload: Uint8Array): Uint8Array {
    if (this.closed) throw new SecureChannelError("closed", "sender closed");
    if (this.nonce >= 2n ** 64n - 1n) throw new SecureChannelError("nonce_exhausted", "reconnect");
    const nonce = this.nonce;
    this.nonce += 1n;
    const plaintext = concatBytes(new Uint8Array([kind]), payload);
    try {
      return this.cipher.encryptWithNonce(nonce, new Uint8Array(0), plaintext);
    } catch (error) {
      throw noiseError(error);
    }
  }

  seal(data: Uint8Array): string {
    const records: Uint8Array[] = [];
    if (data.length === 0) {
      records.push(this.sealRecord(KIND_DATA_FINAL, data));
      return encodeWire(records);
    }
    for (let offset = 0; offset < data.length; offset += MAX_CHUNK_PAYLOAD_LEN) {
      const chunk = data.subarray(offset, Math.min(offset + MAX_CHUNK_PAYLOAD_LEN, data.length));
      const isLast = offset + MAX_CHUNK_PAYLOAD_LEN >= data.length;
      records.push(this.sealRecord(isLast ? KIND_DATA_FINAL : KIND_DATA_MORE, chunk));
    }
    return encodeWire(records);
  }

  sealText(text: string): string {
    return this.seal(utf8Encode(text));
  }

  sealClose(reason: string): string {
    let bytes = utf8Encode(reason);
    if (bytes.length > CLOSE_REASON_MAX_LEN) {
      // Truncate on a character boundary, as the Rust side does.
      let end = CLOSE_REASON_MAX_LEN;
      while (end > 0 && (bytes[end] & 0xc0) === 0x80) end -= 1;
      bytes = bytes.slice(0, end);
    }
    const record = this.sealRecord(KIND_CLOSE, bytes);
    this.closed = true;
    return encodeWire([record]);
  }

  isClosed(): boolean {
    return this.closed;
  }
}

export class ChannelReceiver {
  private nonce = 0n;
  private partial: Uint8Array[] = [];
  private partialLength = 0;
  private closed = false;

  constructor(
    private readonly cipher: CipherState,
    private readonly maxMessageLen: number,
  ) {}

  open(wire: string): Received[] {
    if (this.closed) throw new SecureChannelError("closed", "receiver closed");
    try {
      return this.openInner(wire);
    } catch (error) {
      this.closed = true;
      this.partial = [];
      this.partialLength = 0;
      throw noiseError(error);
    }
  }

  private openInner(wire: string): Received[] {
    const records = decodeWire(wire);
    const received: Received[] = [];
    for (const record of records) {
      if (this.nonce >= 2n ** 64n - 1n) throw new SecureChannelError("nonce_exhausted", "reconnect");
      const plaintext = this.cipher.decryptWithNonce(this.nonce, new Uint8Array(0), record);
      this.nonce += 1n;
      if (plaintext.length === 0) throw new SecureChannelError("wire", "empty record plaintext");
      const kind = plaintext[0];
      const payload = plaintext.subarray(1);
      if (kind === KIND_DATA_MORE || kind === KIND_DATA_FINAL) {
        if (this.partialLength + payload.length > this.maxMessageLen) {
          throw new SecureChannelError("message_too_large", `message exceeds ${this.maxMessageLen} bytes`);
        }
        this.partial.push(payload);
        this.partialLength += payload.length;
        if (kind === KIND_DATA_FINAL) {
          const data = concatBytes(...this.partial);
          this.partial = [];
          this.partialLength = 0;
          received.push({ kind: "message", data });
        }
      } else if (kind === KIND_CLOSE) {
        this.closed = true;
        this.partial = [];
        this.partialLength = 0;
        received.push({ kind: "closed", reason: utf8Decode(payload) });
        return received;
      } else {
        throw new SecureChannelError("wire", "unknown record kind");
      }
    }
    return received;
  }

  isClosed(): boolean {
    return this.closed;
  }
}

export interface Channel {
  handshakeHash: Uint8Array;
  sas: string;
  remoteStatic: Uint8Array;
  sender: ChannelSender;
  receiver: ChannelReceiver;
}

function channelFrom(handshake: HandshakeState, maxMessageLen: number): Channel {
  const keys = handshake.split();
  return {
    handshakeHash: keys.handshakeHash,
    sas: sasCode(keys.handshakeHash),
    remoteStatic: keys.remoteStatic,
    sender: new ChannelSender(keys.send),
    receiver: new ChannelReceiver(keys.receive, maxMessageLen),
  };
}

export interface PendingInitiator {
  message1: string;
  finish(wire: string): { channel: Channel; hello: ResponderHello };
}

/** Phone side: message 1 against the pinned desktop key. */
export function startInitiator(
  local: Keypair,
  remoteStatic: Uint8Array,
  desktopId: string,
  hello: InitiatorHello,
  options: ChannelOptions,
): PendingInitiator {
  const maxMessageLen = options.maxMessageLen ?? DEFAULT_MAX_MESSAGE_LEN;
  let handshake: HandshakeState;
  let message1: string;
  try {
    handshake = new HandshakeState({
      initiator: true,
      prologue: prologue(desktopId),
      localStatic: local,
      remoteStatic,
      randomBytes: options.randomBytes,
      fixedEphemeral: options.fixedEphemeral,
    });
    message1 = encodeWire([handshake.writeMessage1(encodeHello(hello))]);
  } catch (error) {
    throw noiseError(error);
  }
  let finished = false;
  return {
    message1,
    finish(wire) {
      if (finished) throw new SecureChannelError("noise", "handshake already finished");
      finished = true;
      const records = decodeWire(wire);
      if (records.length !== 1) throw new SecureChannelError("wire", "handshake frame must carry exactly one record");
      let payload: Uint8Array;
      try {
        payload = handshake.readMessage2(records[0]);
      } catch (error) {
        throw noiseError(error);
      }
      const responderHello = parseResponderHello(payload);
      return { channel: channelFrom(handshake, maxMessageLen), hello: responderHello };
    },
  };
}

export interface PendingResponder {
  hello: InitiatorHello;
  remoteStatic: Uint8Array;
  accept(hello: ResponderHello): { message2: string; channel: Channel };
}

/** Desktop side (used by tests and the e2e hostile-responder harness). */
export function readInitiatorHello(
  local: Keypair,
  desktopId: string,
  wire: string,
  options: ChannelOptions,
): PendingResponder {
  const maxMessageLen = options.maxMessageLen ?? DEFAULT_MAX_MESSAGE_LEN;
  const records = decodeWire(wire);
  if (records.length !== 1) throw new SecureChannelError("wire", "handshake frame must carry exactly one record");
  let handshake: HandshakeState;
  let payload: Uint8Array;
  try {
    handshake = new HandshakeState({
      initiator: false,
      prologue: prologue(desktopId),
      localStatic: local,
      randomBytes: options.randomBytes,
      fixedEphemeral: options.fixedEphemeral,
    });
    payload = handshake.readMessage1(records[0]);
  } catch (error) {
    throw noiseError(error);
  }
  const hello = parseInitiatorHello(payload);
  let accepted = false;
  return {
    hello,
    remoteStatic: handshake.remoteStatic(),
    accept(responderHello) {
      if (accepted) throw new SecureChannelError("noise", "handshake already finished");
      accepted = true;
      let message2: string;
      try {
        message2 = encodeWire([handshake.writeMessage2(encodeHello(responderHello))]);
      } catch (error) {
        throw noiseError(error);
      }
      return { message2, channel: channelFrom(handshake, maxMessageLen) };
    },
  };
}

export function keysEqual(left: Uint8Array, right: Uint8Array): boolean {
  return bytesEqual(left, right);
}
