// A spec-exact implementation of the Noise Protocol Framework's `IK`
// handshake and transport for `Noise_IK_25519_ChaChaPoly_SHA256`
// (https://noiseprotocol.org/noise.html, revision 34), built only from the
// audited `@noble` primitives. Nothing here is a Kanna-specific construction:
// every state machine, key schedule and nonce encoding follows the
// specification sections named inline, and the package's test suite runs the
// published cacophony vector plus vectors generated by the Rust `snow`
// implementation through this file.
//
// Why hand-write the pattern at all: the Rust side uses `snow`; there is no
// maintained, Hermes-compatible TypeScript Noise library with test vectors
// that this repository could vendor, and a 200-line spec transcription that
// is gated by the official vectors is a smaller trust surface than an
// unmaintained dependency would be.

import { chacha20poly1305 } from "@noble/ciphers/chacha.js";
import { x25519 } from "@noble/curves/ed25519.js";
import { hmac } from "@noble/hashes/hmac.js";
import { sha256 } from "@noble/hashes/sha2.js";
import { concatBytes, utf8Encode } from "./bytes";

export const NOISE_PROTOCOL_NAME = "Noise_IK_25519_ChaChaPoly_SHA256";
export const DHLEN = 32;
export const HASHLEN = 32;
export const TAGLEN = 16;
/** Noise §3: the maximum length of any handshake or transport message. */
export const MAX_NOISE_MESSAGE_LEN = 65_535;
/** Noise §5.1: `n` is reserved at 2^64-1; we refuse well before that. */
const MAX_NONCE = 2n ** 64n - 2n;

export type RandomBytes = (length: number) => Uint8Array;

export interface Keypair {
  privateKey: Uint8Array;
  publicKey: Uint8Array;
}

export function generateKeypair(randomBytes: RandomBytes): Keypair {
  const privateKey = randomBytes(DHLEN);
  if (!(privateKey instanceof Uint8Array) || privateKey.length !== DHLEN) {
    throw new Error("noise: random source did not return 32 bytes");
  }
  return keypairFromPrivate(privateKey);
}

export function keypairFromPrivate(privateKey: Uint8Array): Keypair {
  if (privateKey.length !== DHLEN) throw new Error("noise: private key must be 32 bytes");
  return { privateKey, publicKey: x25519.getPublicKey(privateKey) };
}

/** Noise §4.1 DH. */
function dh(keypair: Keypair, remotePublic: Uint8Array): Uint8Array {
  return x25519.getSharedSecret(keypair.privateKey, remotePublic);
}

/** Noise §12.3: ChaChaPoly nonce is 32 bits of zeros followed by the
 * 64-bit little-endian encoding of `n`. */
function chachaNonce(n: bigint): Uint8Array {
  const nonce = new Uint8Array(12);
  let value = n;
  for (let index = 4; index < 12; index += 1) {
    nonce[index] = Number(value & 0xffn);
    value >>= 8n;
  }
  return nonce;
}

/** Noise §5.1 CipherState. */
export class CipherState {
  private key: Uint8Array | null = null;
  private nonce = 0n;

  initializeKey(key: Uint8Array | null): void {
    this.key = key;
    this.nonce = 0n;
  }

  hasKey(): boolean {
    return this.key !== null;
  }

  private takeNonce(): bigint {
    if (this.nonce > MAX_NONCE) throw new Error("noise: nonce exhausted");
    const current = this.nonce;
    this.nonce += 1n;
    return current;
  }

  encryptWithAd(ad: Uint8Array, plaintext: Uint8Array): Uint8Array {
    if (this.key === null) return plaintext;
    const nonce = this.takeNonce();
    return chacha20poly1305(this.key, chachaNonce(nonce), ad).encrypt(plaintext);
  }

  decryptWithAd(ad: Uint8Array, ciphertext: Uint8Array): Uint8Array {
    if (this.key === null) return ciphertext;
    const nonce = this.takeNonce();
    try {
      return chacha20poly1305(this.key, chachaNonce(nonce), ad).decrypt(ciphertext);
    } catch {
      // The nonce was consumed: a failed decryption ends the stream, which
      // is what the caller must enforce (Noise §5.1: "If DECRYPT() fails ...").
      throw new Error("noise: decryption failed");
    }
  }

  /** Stateless variants for split use: explicit nonces, no internal
   * counter, so a sender and a receiver can share one key without racing. */
  encryptWithNonce(n: bigint, ad: Uint8Array, plaintext: Uint8Array): Uint8Array {
    if (this.key === null) throw new Error("noise: no key");
    if (n > MAX_NONCE) throw new Error("noise: nonce exhausted");
    return chacha20poly1305(this.key, chachaNonce(n), ad).encrypt(plaintext);
  }

  decryptWithNonce(n: bigint, ad: Uint8Array, ciphertext: Uint8Array): Uint8Array {
    if (this.key === null) throw new Error("noise: no key");
    if (n > MAX_NONCE) throw new Error("noise: nonce exhausted");
    try {
      return chacha20poly1305(this.key, chachaNonce(n), ad).decrypt(ciphertext);
    } catch {
      throw new Error("noise: decryption failed");
    }
  }
}

/** Noise §4.3 HKDF with `num_outputs` of 2 (the only case IK needs). */
function noiseHkdf2(chainingKey: Uint8Array, inputKeyMaterial: Uint8Array): [Uint8Array, Uint8Array] {
  const tempKey = hmac(sha256, chainingKey, inputKeyMaterial);
  const output1 = hmac(sha256, tempKey, new Uint8Array([0x01]));
  const output2 = hmac(sha256, tempKey, concatBytes(output1, new Uint8Array([0x02])));
  return [output1, output2];
}

/** Noise §5.2 SymmetricState. */
export class SymmetricState {
  readonly cipher = new CipherState();
  private ck: Uint8Array;
  private h: Uint8Array;

  constructor(protocolName: string) {
    const name = utf8Encode(protocolName);
    if (name.length <= HASHLEN) {
      this.h = new Uint8Array(HASHLEN);
      this.h.set(name);
    } else {
      this.h = sha256(name);
    }
    this.ck = this.h.slice();
    this.cipher.initializeKey(null);
  }

  mixKey(inputKeyMaterial: Uint8Array): void {
    const [ck, tempKey] = noiseHkdf2(this.ck, inputKeyMaterial);
    this.ck = ck;
    this.cipher.initializeKey(tempKey);
  }

  mixHash(data: Uint8Array): void {
    this.h = sha256(concatBytes(this.h, data));
  }

  encryptAndHash(plaintext: Uint8Array): Uint8Array {
    const ciphertext = this.cipher.encryptWithAd(this.h, plaintext);
    this.mixHash(ciphertext);
    return ciphertext;
  }

  decryptAndHash(ciphertext: Uint8Array): Uint8Array {
    const plaintext = this.cipher.decryptWithAd(this.h, ciphertext);
    this.mixHash(ciphertext);
    return plaintext;
  }

  split(): [CipherState, CipherState] {
    const [k1, k2] = noiseHkdf2(this.ck, new Uint8Array(0));
    const c1 = new CipherState();
    c1.initializeKey(k1);
    const c2 = new CipherState();
    c2.initializeKey(k2);
    return [c1, c2];
  }

  handshakeHash(): Uint8Array {
    return this.h.slice();
  }
}

export interface HandshakeOptions {
  initiator: boolean;
  prologue: Uint8Array;
  localStatic: Keypair;
  /** Required for the initiator (IK pre-message `<- s`). */
  remoteStatic?: Uint8Array;
  randomBytes: RandomBytes;
  /** Deterministic ephemeral for test vectors only. */
  fixedEphemeral?: Uint8Array;
}

/** Split transport keys: `send` is this side's sending CipherState. */
export interface TransportKeys {
  send: CipherState;
  receive: CipherState;
  handshakeHash: Uint8Array;
  remoteStatic: Uint8Array;
}

/**
 * Noise §5.3 HandshakeState specialised to IK:
 *
 * ```
 *   <- s
 *   ...
 *   -> e, es, s, ss
 *   <- e, ee, se
 * ```
 */
export class HandshakeState {
  private readonly symmetric = new SymmetricState(NOISE_PROTOCOL_NAME);
  private readonly initiator: boolean;
  private readonly s: Keypair;
  private e: Keypair | null = null;
  private rs: Uint8Array | null;
  private re: Uint8Array | null = null;
  private readonly randomBytes: RandomBytes;
  private readonly fixedEphemeral: Uint8Array | undefined;
  private step: "write1" | "read1" | "write2" | "read2" | "done";

  constructor(options: HandshakeOptions) {
    this.initiator = options.initiator;
    this.s = options.localStatic;
    this.rs = options.remoteStatic ?? null;
    this.randomBytes = options.randomBytes;
    this.fixedEphemeral = options.fixedEphemeral;
    if (this.initiator && !this.rs) throw new Error("noise: IK initiator needs the remote static key");
    if (this.rs && this.rs.length !== DHLEN) throw new Error("noise: remote static must be 32 bytes");
    this.symmetric.mixHash(options.prologue);
    // Pre-message `<- s`: the responder's static, known to both in advance.
    this.symmetric.mixHash(this.initiator ? (this.rs as Uint8Array) : this.s.publicKey);
    this.step = this.initiator ? "write1" : "read1";
  }

  private generateEphemeral(): Keypair {
    if (this.fixedEphemeral) return keypairFromPrivate(this.fixedEphemeral);
    return generateKeypair(this.randomBytes);
  }

  /** `-> e, es, s, ss` from the initiator. */
  writeMessage1(payload: Uint8Array): Uint8Array {
    if (this.step !== "write1") throw new Error("noise: not the initiator's first turn");
    const rs = this.rs as Uint8Array;
    this.e = this.generateEphemeral();
    this.symmetric.mixHash(this.e.publicKey);
    this.symmetric.mixKey(dh(this.e, rs)); // es
    const encryptedStatic = this.symmetric.encryptAndHash(this.s.publicKey); // s
    this.symmetric.mixKey(dh(this.s, rs)); // ss
    const encryptedPayload = this.symmetric.encryptAndHash(payload);
    this.step = "read2";
    const message = concatBytes(this.e.publicKey, encryptedStatic, encryptedPayload);
    if (message.length > MAX_NOISE_MESSAGE_LEN) throw new Error("noise: message too long");
    return message;
  }

  /** `-> e, es, s, ss` read by the responder. */
  readMessage1(message: Uint8Array): Uint8Array {
    if (this.step !== "read1") throw new Error("noise: not the responder's first turn");
    if (message.length < DHLEN + DHLEN + TAGLEN + TAGLEN) throw new Error("noise: message 1 too short");
    let offset = 0;
    this.re = message.slice(offset, offset + DHLEN);
    offset += DHLEN;
    this.symmetric.mixHash(this.re);
    this.symmetric.mixKey(dh(this.s, this.re)); // es (responder: DH(s, re))
    const encryptedStatic = message.slice(offset, offset + DHLEN + TAGLEN);
    offset += DHLEN + TAGLEN;
    this.rs = this.symmetric.decryptAndHash(encryptedStatic); // s
    this.symmetric.mixKey(dh(this.s, this.rs)); // ss
    const payload = this.symmetric.decryptAndHash(message.slice(offset));
    this.step = "write2";
    return payload;
  }

  /** `<- e, ee, se` from the responder. */
  writeMessage2(payload: Uint8Array): Uint8Array {
    if (this.step !== "write2") throw new Error("noise: not the responder's turn");
    const re = this.re as Uint8Array;
    const rs = this.rs as Uint8Array;
    this.e = this.generateEphemeral();
    this.symmetric.mixHash(this.e.publicKey);
    this.symmetric.mixKey(dh(this.e, re)); // ee
    this.symmetric.mixKey(dh(this.e, rs)); // se (responder: DH(e, rs))
    const encryptedPayload = this.symmetric.encryptAndHash(payload);
    this.step = "done";
    const message = concatBytes(this.e.publicKey, encryptedPayload);
    if (message.length > MAX_NOISE_MESSAGE_LEN) throw new Error("noise: message too long");
    return message;
  }

  /** `<- e, ee, se` read by the initiator. */
  readMessage2(message: Uint8Array): Uint8Array {
    if (this.step !== "read2") throw new Error("noise: not the initiator's second turn");
    if (message.length < DHLEN + TAGLEN) throw new Error("noise: message 2 too short");
    const e = this.e as Keypair;
    this.re = message.slice(0, DHLEN);
    this.symmetric.mixHash(this.re);
    this.symmetric.mixKey(dh(e, this.re)); // ee
    this.symmetric.mixKey(dh(this.s, this.re)); // se (initiator: DH(s, re))
    const payload = this.symmetric.decryptAndHash(message.slice(DHLEN));
    this.step = "done";
    return payload;
  }

  remoteStatic(): Uint8Array {
    if (!this.rs) throw new Error("noise: remote static unknown");
    return this.rs.slice();
  }

  handshakeHash(): Uint8Array {
    return this.symmetric.handshakeHash();
  }

  /** Noise §5.3 Split: the initiator sends with the first CipherState. */
  split(): TransportKeys {
    if (this.step !== "done") throw new Error("noise: handshake not finished");
    const [c1, c2] = this.symmetric.split();
    return {
      send: this.initiator ? c1 : c2,
      receive: this.initiator ? c2 : c1,
      handshakeHash: this.symmetric.handshakeHash(),
      remoteStatic: this.remoteStatic(),
    };
  }
}
