import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { bytesToHex, decodeBase64, hexToBytes, utf8Encode } from "./bytes";
import { HandshakeState, keypairFromPrivate } from "./noise";
import {
  readInitiatorHello,
  sasCode,
  startInitiator,
  type InitiatorHello,
  type ResponderHello,
} from "./channel";

const vectorsDir = new URL("../../../tests/secure-channel-vectors/", import.meta.url);

function readJson<T>(name: string): T {
  return JSON.parse(readFileSync(fileURLToPath(new URL(name, vectorsDir)), "utf8")) as T;
}

const noRandom = () => {
  throw new Error("vector runs must not draw randomness");
};

interface OfficialVector {
  protocol_name: string;
  init_prologue: string;
  init_static: string;
  init_ephemeral: string;
  init_remote_static: string;
  resp_prologue: string;
  resp_static: string;
  resp_ephemeral: string;
  handshake_hash: string;
  messages: { payload: string; ciphertext: string }[];
}

describe("published Noise_IK_25519_ChaChaPoly_SHA256 vector", () => {
  const file = readJson<{ vectors: OfficialVector[] }>("noise-ik-25519-chachapoly-sha256.json");

  it.each(file.vectors.map((vector, index) => [index, vector] as const))(
    "vector %i reproduces every handshake and transport ciphertext",
    (_index, vector) => {
      expect(vector.protocol_name).toBe("Noise_IK_25519_ChaChaPoly_SHA256");
      const initiatorStatic = keypairFromPrivate(hexToBytes(vector.init_static));
      const responderStatic = keypairFromPrivate(hexToBytes(vector.resp_static));
      expect(bytesToHex(responderStatic.publicKey)).toBe(vector.init_remote_static);
      const initiator = new HandshakeState({
        initiator: true,
        prologue: hexToBytes(vector.init_prologue),
        localStatic: initiatorStatic,
        remoteStatic: hexToBytes(vector.init_remote_static),
        randomBytes: noRandom,
        fixedEphemeral: hexToBytes(vector.init_ephemeral),
      });
      const responder = new HandshakeState({
        initiator: false,
        prologue: hexToBytes(vector.resp_prologue),
        localStatic: responderStatic,
        randomBytes: noRandom,
        fixedEphemeral: hexToBytes(vector.resp_ephemeral),
      });
      const [first, second, ...transport] = vector.messages;
      const message1 = initiator.writeMessage1(hexToBytes(first.payload));
      expect(bytesToHex(message1)).toBe(first.ciphertext);
      expect(bytesToHex(responder.readMessage1(message1))).toBe(first.payload);
      const message2 = responder.writeMessage2(hexToBytes(second.payload));
      expect(bytesToHex(message2)).toBe(second.ciphertext);
      expect(bytesToHex(initiator.readMessage2(message2))).toBe(second.payload);
      expect(bytesToHex(initiator.handshakeHash())).toBe(vector.handshake_hash);
      expect(bytesToHex(responder.handshakeHash())).toBe(vector.handshake_hash);
      expect(bytesToHex(responder.remoteStatic())).toBe(bytesToHex(initiatorStatic.publicKey));

      const initiatorKeys = initiator.split();
      const responderKeys = responder.split();
      transport.forEach((message, offset) => {
        const initiatorSends = offset % 2 === 0;
        const writer = initiatorSends ? initiatorKeys.send : responderKeys.send;
        const reader = initiatorSends ? responderKeys.receive : initiatorKeys.receive;
        const ciphertext = writer.encryptWithAd(new Uint8Array(0), hexToBytes(message.payload));
        expect(bytesToHex(ciphertext)).toBe(message.ciphertext);
        expect(bytesToHex(reader.decryptWithAd(new Uint8Array(0), ciphertext))).toBe(message.payload);
      });
    },
  );
});

interface Frame {
  kind: "data" | "close";
  plaintextBase64?: string;
  reason?: string;
  wire: string;
}

interface CrossLanguageVectors {
  desktopId: string;
  initiatorStaticPrivate: string;
  initiatorStaticPublic: string;
  initiatorEphemeral: string;
  responderStaticPrivate: string;
  responderStaticPublic: string;
  responderEphemeral: string;
  initiatorHello: InitiatorHello;
  responderHello: ResponderHello;
  message1: string;
  message2: string;
  handshakeHash: string;
  sas: string;
  initiatorToResponder: Frame[];
  responderToInitiator: Frame[];
}

describe("cross-language vectors generated by the Rust snow implementation", () => {
  const vectors = readJson<CrossLanguageVectors>("ksc-cross-language.json");
  const initiatorStatic = keypairFromPrivate(hexToBytes(vectors.initiatorStaticPrivate));
  const responderStatic = keypairFromPrivate(hexToBytes(vectors.responderStaticPrivate));

  it("derives the same public keys", () => {
    expect(bytesToHex(initiatorStatic.publicKey)).toBe(vectors.initiatorStaticPublic);
    expect(bytesToHex(responderStatic.publicKey)).toBe(vectors.responderStaticPublic);
  });

  it("as initiator reproduces message 1, accepts Rust's message 2 and every transport frame", () => {
    const pending = startInitiator(
      initiatorStatic,
      hexToBytes(vectors.responderStaticPublic),
      vectors.desktopId,
      vectors.initiatorHello,
      { randomBytes: noRandom, fixedEphemeral: hexToBytes(vectors.initiatorEphemeral) },
    );
    expect(pending.message1).toBe(vectors.message1);
    const { channel, hello } = pending.finish(vectors.message2);
    expect(hello).toEqual({ ...vectors.responderHello, capabilities: vectors.responderHello.capabilities ?? [] });
    expect(bytesToHex(channel.handshakeHash)).toBe(vectors.handshakeHash);
    expect(channel.sas).toBe(vectors.sas);
    expect(sasCode(channel.handshakeHash)).toBe(vectors.sas);
    expect(bytesToHex(channel.remoteStatic)).toBe(vectors.responderStaticPublic);

    for (const frame of vectors.initiatorToResponder) {
      if (frame.kind === "data") {
        expect(channel.sender.seal(decodeBase64(frame.plaintextBase64 ?? ""))).toBe(frame.wire);
      } else {
        expect(channel.sender.sealClose(frame.reason ?? "")).toBe(frame.wire);
      }
    }
    for (const frame of vectors.responderToInitiator) {
      const received = channel.receiver.open(frame.wire);
      if (frame.kind === "data") {
        expect(received).toEqual([{ kind: "message", data: decodeBase64(frame.plaintextBase64 ?? "") }]);
      } else {
        expect(received).toEqual([{ kind: "closed", reason: frame.reason ?? "" }]);
      }
    }
  });

  it("as responder accepts Rust's message 1, reproduces message 2 and every transport frame", () => {
    const pending = readInitiatorHello(responderStatic, vectors.desktopId, vectors.message1, {
      randomBytes: noRandom,
      fixedEphemeral: hexToBytes(vectors.responderEphemeral),
    });
    expect(pending.hello).toEqual({
      ...vectors.initiatorHello,
      capabilities: vectors.initiatorHello.capabilities ?? [],
    });
    expect(bytesToHex(pending.remoteStatic)).toBe(vectors.initiatorStaticPublic);
    const { message2, channel } = pending.accept(vectors.responderHello);
    expect(message2).toBe(vectors.message2);
    expect(bytesToHex(channel.handshakeHash)).toBe(vectors.handshakeHash);
    expect(channel.sas).toBe(vectors.sas);

    for (const frame of vectors.initiatorToResponder) {
      const received = channel.receiver.open(frame.wire);
      if (frame.kind === "data") {
        expect(received).toEqual([{ kind: "message", data: decodeBase64(frame.plaintextBase64 ?? "") }]);
      } else {
        expect(received).toEqual([{ kind: "closed", reason: frame.reason ?? "" }]);
      }
    }
    for (const frame of vectors.responderToInitiator) {
      if (frame.kind === "data") {
        expect(channel.sender.seal(decodeBase64(frame.plaintextBase64 ?? ""))).toBe(frame.wire);
      } else {
        expect(channel.sender.sealClose(frame.reason ?? "")).toBe(frame.wire);
      }
    }
  });

  it("never leaks the hello or a KSP frame in the clear", () => {
    const marker = utf8Encode("term_input_boundary");
    const wires = [vectors.message1, vectors.message2, ...vectors.initiatorToResponder.map((frame) => frame.wire)];
    for (const wire of wires) {
      expect(wire.startsWith("ksc1:")).toBe(true);
      expect(wire).not.toContain("mobile-vector-device");
      expect(wire).not.toContain("auth");
      const bytes = decodeBase64(wire.slice("ksc1:".length));
      expect(bytesToHex(bytes)).not.toContain(bytesToHex(marker));
    }
  });
});
