load("@kanna_server_crates//:defs.bzl", all_crate_deps_for_server = "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_library")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "cargo_srcs",
    srcs = [
        "Cargo.toml",
    ] + glob(["src/**/*.rs"]),
)

rust_library(
    name = "kanna_secure_channel_for_server",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    crate_name = "kanna_secure_channel",
    edition = "2021",
    deps = all_crate_deps_for_server(
        normal = True,
        package_name = "crates/kanna-secure-channel",
    ),
    proc_macro_deps = all_crate_deps_for_server(
        proc_macro = True,
        package_name = "crates/kanna-secure-channel",
    ),
)
