load("@agent_tui_crates//:defs.bzl", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "cargo_srcs",
    srcs = ["Cargo.lock", "Cargo.toml"] + glob(["src/**/*.rs", "assets/**"]),
)

rust_library(
    name = "agent_tui_lib",
    srcs = glob(["src/**/*.rs"], exclude = ["src/main.rs"]),
    crate_root = "src/lib.rs",
    crate_name = "agent_tui",
    edition = "2021",
    version = "0.1.0",
    deps = all_crate_deps(normal = True, package_name = "crates/agent-tui") + ["//crates/kanna-agent-protocol:kanna_agent_protocol_for_agent_tui"],
    proc_macro_deps = all_crate_deps(proc_macro = True, package_name = "crates/agent-tui"),
)

rust_binary(
    name = "agent_tui",
    srcs = ["src/main.rs"],
    crate_root = "src/main.rs",
    crate_name = "agent_tui",
    edition = "2021",
    version = "0.1.0",
    deps = all_crate_deps(normal = True, package_name = "crates/agent-tui") + ["//crates/kanna-agent-protocol:kanna_agent_protocol_for_agent_tui"] + [":agent_tui_lib"],
    proc_macro_deps = all_crate_deps(proc_macro = True, package_name = "crates/agent-tui"),
)

rust_binary(
    name = "agent_tui_x86_64",
    srcs = ["src/main.rs"],
    crate_root = "src/main.rs",
    crate_name = "agent_tui",
    edition = "2021",
    version = "0.1.0",
    deps = all_crate_deps(normal = True, package_name = "crates/agent-tui") + ["//crates/kanna-agent-protocol:kanna_agent_protocol_for_agent_tui"] + [":agent_tui_lib"],
    proc_macro_deps = all_crate_deps(proc_macro = True, package_name = "crates/agent-tui"),
    platform = "//tools/bazel:macos_x86_64",
)
