const fs = require("node:fs");
const path = require("node:path");
const {
  AndroidConfig,
  IOSConfig,
  withAndroidManifest,
  withDangerousMod,
  withInfoPlist,
  withMainApplication,
  withXcodeProject
} = require("expo/config-plugins");

const SERVICE_TYPE = "_kanna-mobile._tcp";
const LOCAL_NETWORK_USAGE_DESCRIPTION =
  "Kanna uses your local network to find and connect to your paired Kanna desktop app.";
const ANDROID_MODULE_NAME = "KannaBonjourModule";
const ANDROID_PACKAGE_CLASS = "KannaBonjourPackage";
const NETWORK_SECURITY_CONFIG_RESOURCE = "kanna_network_security_config";

const SWIFT_SOURCE = `import Foundation
import React

@objc(KannaBonjourModule)
final class KannaBonjourModule: RCTEventEmitter, NetServiceBrowserDelegate, NetServiceDelegate {
  private let browser = NetServiceBrowser()
  private var services: [String: NetService] = [:]

  override init() {
    super.init()
    browser.delegate = self
  }

  override static func requiresMainQueueSetup() -> Bool {
    false
  }

  override func supportedEvents() -> [String]! {
    ["kannaBonjourServiceChanged"]
  }

  @objc(startBrowsing)
  func startBrowsing() {
    browser.searchForServices(ofType: "${SERVICE_TYPE}.", inDomain: "local.")
  }

  @objc(stopBrowsing)
  func stopBrowsing() {
    browser.stop()
    services.removeAll()
  }

  func netServiceBrowser(_ browser: NetServiceBrowser, didFind service: NetService, moreComing: Bool) {
    services[service.name] = service
    service.delegate = self
    service.resolve(withTimeout: 5)
  }

  func netServiceBrowser(_ browser: NetServiceBrowser, didRemove service: NetService, moreComing: Bool) {
    services.removeValue(forKey: service.name)
    sendService(service, removed: true)
  }

  func netServiceDidResolveAddress(_ sender: NetService) {
    sendService(sender, removed: false)
  }

  private func sendService(_ service: NetService, removed: Bool) {
    var txt: [String: String] = [:]
    if let data = service.txtRecordData() {
      for (key, value) in NetService.dictionary(fromTXTRecord: data) {
        txt[key] = String(data: value, encoding: .utf8) ?? ""
      }
    }

    sendEvent(
      withName: "kannaBonjourServiceChanged",
      body: [
        "name": service.name,
        "type": service.type,
        "host": service.hostName ?? "",
        "port": service.port,
        "txt": txt,
        "removed": removed
      ]
    )
  }
}
`;

const OBJC_SOURCE = `#import <React/RCTBridgeModule.h>
#import <React/RCTEventEmitter.h>

@interface RCT_EXTERN_MODULE(KannaBonjourModule, RCTEventEmitter)

RCT_EXTERN_METHOD(startBrowsing)
RCT_EXTERN_METHOD(stopBrowsing)

@end
`;

/**
 * Android half of discovery. iOS browses with NetServiceBrowser; Android has no
 * equivalent of that framework, so this module drives the platform NsdManager
 * and emits the same `kannaBonjourServiceChanged` events, keeping one JS
 * browser (src/lib/discovery/bonjour.ts) for both platforms.
 */
function androidModuleSource(packageName) {
  return `package ${packageName}

import android.content.Context
import android.net.nsd.NsdManager
import android.net.nsd.NsdServiceInfo
import android.os.Build
import android.os.Handler
import android.os.Looper
import android.util.Log
import com.facebook.react.bridge.Arguments
import com.facebook.react.bridge.LifecycleEventListener
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod
import com.facebook.react.bridge.WritableMap
import java.net.Inet6Address
import java.net.InetAddress
import java.util.concurrent.Executor

/**
 * Generated by apps/mobile/plugins/withKannaBonjour.js. Edit the plugin, not
 * this file: prebuild overwrites it.
 *
 * Browses "_kanna-mobile._tcp" with the platform NsdManager and reports each
 * resolved desktop to JS in the same event shape KannaBonjourModule.swift uses.
 * Every piece of state below is owned by the main thread; NsdManager delivers
 * its callbacks on its own threads and React delivers method calls on the
 * native-modules thread, so both hop onto [mainHandler] first.
 */
class ${ANDROID_MODULE_NAME}(reactContext: ReactApplicationContext) :
  ReactContextBaseJavaModule(reactContext), LifecycleEventListener {

  private val mainHandler = Handler(Looper.getMainLooper())
  private val callbackExecutor = Executor { command -> mainHandler.post(command) }
  private val nsdManager: NsdManager? =
    reactContext.applicationContext.getSystemService(Context.NSD_SERVICE) as? NsdManager

  /** What JS asked for. Survives a foreground/background cycle. */
  private var browsingRequested = false
  private var discoveryListener: NsdManager.DiscoveryListener? = null
  private var discoveryActive = false

  /**
   * Fences callbacks belonging to a browse that has already been torn down.
   * NsdManager keeps delivering to a stopped listener until the platform
   * confirms the stop, and a late resolve would otherwise resurrect a desktop
   * that is no longer there.
   */
  private var browseGeneration = 0
  private val startPromises = mutableListOf<Promise>()
  private val serviceCallbacks = mutableMapOf<String, Any>()
  private val pendingResolves = ArrayDeque<NsdServiceInfo>()
  private var resolving = false

  init {
    reactContext.addLifecycleEventListener(this)
  }

  override fun getName(): String = NAME

  // NativeEventEmitter's bookkeeping. Kanna emits from native state, so these
  // only have to exist.
  @ReactMethod
  fun addListener(eventName: String) = Unit

  @ReactMethod
  fun removeListeners(count: Int) = Unit

  @ReactMethod
  fun startBrowsing() {
    mainHandler.post { startDiscovery(null) }
  }

  /**
   * Starts discovery and settles once the platform confirms the browse is
   * running, so a pairing attempt can tell "nothing is advertising" from "this
   * device cannot browse at all".
   */
  @ReactMethod
  fun ensureBrowsing(promise: Promise) {
    mainHandler.post {
      if (discoveryActive) {
        promise.resolve(null)
      } else {
        startDiscovery(promise)
      }
    }
  }

  @ReactMethod
  fun stopBrowsing() {
    mainHandler.post {
      browsingRequested = false
      stopDiscovery("Discovery stopped.")
    }
  }

  override fun onHostResume() {
    mainHandler.post {
      if (browsingRequested && discoveryListener == null) startDiscovery(null)
    }
  }

  override fun onHostPause() {
    mainHandler.post { stopDiscovery("The app left the foreground.") }
  }

  override fun onHostDestroy() {
    mainHandler.post {
      browsingRequested = false
      stopDiscovery("The app was destroyed.")
    }
  }

  override fun invalidate() {
    reactApplicationContext.removeLifecycleEventListener(this)
    mainHandler.post {
      browsingRequested = false
      stopDiscovery("The React instance went away.")
    }
    super.invalidate()
  }

  private fun startDiscovery(promise: Promise?) {
    browsingRequested = true
    val manager = nsdManager
    if (manager == null) {
      promise?.reject(ERROR_CODE, "This device does not support network service discovery.")
      return
    }
    if (promise != null) startPromises.add(promise)
    if (discoveryListener != null) return

    browseGeneration += 1
    val browse = browseGeneration
    val listener = object : NsdManager.DiscoveryListener {
      override fun onDiscoveryStarted(serviceType: String) = onMain(browse) {
        discoveryActive = true
        settleStartPromises(null)
      }

      override fun onStartDiscoveryFailed(serviceType: String, errorCode: Int) = onMain(browse) {
        discoveryListener = null
        discoveryActive = false
        settleStartPromises("Network service discovery could not start (code " + errorCode + ").")
      }

      override fun onDiscoveryStopped(serviceType: String) = onMain(browse) {
        discoveryActive = false
      }

      override fun onStopDiscoveryFailed(serviceType: String, errorCode: Int) = onMain(browse) {
        discoveryActive = false
      }

      override fun onServiceFound(serviceInfo: NsdServiceInfo) = onMain(browse) {
        trackService(serviceInfo, browse)
      }

      override fun onServiceLost(serviceInfo: NsdServiceInfo) = onMain(browse) {
        forgetService(serviceInfo.serviceName)
      }
    }
    discoveryListener = listener
    try {
      manager.discoverServices(DISCOVERY_SERVICE_TYPE, NsdManager.PROTOCOL_DNS_SD, listener)
    } catch (error: Throwable) {
      Log.w(NAME, "Could not browse for Kanna desktops.", error)
      discoveryListener = null
      discoveryActive = false
      settleStartPromises(error.message ?: "Network service discovery could not start.")
    }
  }

  private fun stopDiscovery(reason: String) {
    browseGeneration += 1
    discoveryActive = false
    settleStartPromises(reason)
    unregisterServiceCallbacks()
    pendingResolves.clear()
    resolving = false
    val manager = nsdManager
    val listener = discoveryListener
    discoveryListener = null
    if (manager == null || listener == null) return
    try {
      manager.stopServiceDiscovery(listener)
    } catch (error: Throwable) {
      // Already stopped by the platform; the generation fence drops whatever is
      // still in flight.
      Log.d(NAME, "Discovery was already stopped.", error)
    }
  }

  private fun settleStartPromises(error: String?) {
    if (startPromises.isEmpty()) return
    val promises = startPromises.toList()
    startPromises.clear()
    for (promise in promises) {
      if (error == null) promise.resolve(null) else promise.reject(ERROR_CODE, error)
    }
  }

  private fun trackService(serviceInfo: NsdServiceInfo, browse: Int) {
    val manager = nsdManager ?: return
    val name = serviceInfo.serviceName ?: return
    if (Build.VERSION.SDK_INT >= SERVICE_INFO_CALLBACK_SDK) {
      if (serviceCallbacks.containsKey(name)) return
      watchService(manager, serviceInfo, name, browse)
      return
    }
    // Older platforms resolve one service at a time; a second concurrent
    // resolve fails with "listener already in use".
    pendingResolves.addLast(serviceInfo)
    drainResolves(browse)
  }

  /**
   * API 34+ path. Kept in its own method so the callback class is only loaded
   * on platforms that have it.
   */
  private fun watchService(
    manager: NsdManager,
    serviceInfo: NsdServiceInfo,
    name: String,
    browse: Int
  ) {
    val callback = object : NsdManager.ServiceInfoCallback {
      override fun onServiceInfoCallbackRegistrationFailed(errorCode: Int) = onMain(browse) {
        serviceCallbacks.remove(name)
      }

      override fun onServiceUpdated(serviceInfo: NsdServiceInfo) = onMain(browse) {
        emitService(serviceInfo)
      }

      override fun onServiceLost() = onMain(browse) { forgetService(name) }

      override fun onServiceInfoCallbackUnregistered() = Unit
    }
    serviceCallbacks[name] = callback
    try {
      manager.registerServiceInfoCallback(serviceInfo, callbackExecutor, callback)
    } catch (error: Throwable) {
      Log.w(NAME, "Could not watch a discovered Kanna desktop.", error)
      serviceCallbacks.remove(name)
    }
  }

  private fun drainResolves(browse: Int) {
    if (resolving) return
    val manager = nsdManager ?: return
    val next = pendingResolves.removeFirstOrNull() ?: return
    resolving = true
    @Suppress("DEPRECATION")
    manager.resolveService(next, object : NsdManager.ResolveListener {
      override fun onResolveFailed(serviceInfo: NsdServiceInfo, errorCode: Int) = onMain(browse) {
        resolving = false
        drainResolves(browse)
      }

      override fun onServiceResolved(serviceInfo: NsdServiceInfo) = onMain(browse) {
        resolving = false
        emitService(serviceInfo)
        drainResolves(browse)
      }
    })
  }

  private fun unregisterServiceCallbacks() {
    if (serviceCallbacks.isEmpty()) return
    val callbacks = serviceCallbacks.values.toList()
    serviceCallbacks.clear()
    val manager = nsdManager ?: return
    if (Build.VERSION.SDK_INT < SERVICE_INFO_CALLBACK_SDK) return
    unregisterServiceInfoCallbacks(manager, callbacks)
  }

  private fun unregisterServiceInfoCallbacks(manager: NsdManager, callbacks: List<Any>) {
    for (callback in callbacks) {
      if (callback !is NsdManager.ServiceInfoCallback) continue
      try {
        manager.unregisterServiceInfoCallback(callback)
      } catch (error: Throwable) {
        Log.d(NAME, "A desktop watch was already unregistered.", error)
      }
    }
  }

  private fun forgetService(rawName: String?) {
    val name = rawName ?: return
    val callback = serviceCallbacks.remove(name)
    val manager = nsdManager
    if (callback != null && manager != null && Build.VERSION.SDK_INT >= SERVICE_INFO_CALLBACK_SDK) {
      unregisterServiceInfoCallbacks(manager, listOf(callback))
    }
    val event = Arguments.createMap()
    event.putString("name", name)
    event.putString("type", EVENT_SERVICE_TYPE)
    event.putBoolean("removed", true)
    emit(event)
  }

  private fun emitService(serviceInfo: NsdServiceInfo) {
    val host = resolveHost(serviceInfo)
    val port = serviceInfo.port
    if (host.isEmpty() || port <= 0) return

    val txt = Arguments.createMap()
    for (attribute in serviceInfo.attributes.entries) {
      val value = attribute.value
      txt.putString(attribute.key, if (value == null) "" else String(value, Charsets.UTF_8))
    }

    val event = Arguments.createMap()
    event.putString("name", serviceInfo.serviceName ?: "")
    event.putString("type", EVENT_SERVICE_TYPE)
    event.putString("host", host)
    event.putInt("port", port)
    event.putMap("txt", txt)
    event.putBoolean("removed", false)
    emit(event)
  }

  /**
   * Prefers the advertised mDNS hostname. Kanna's shipped Android builds permit
   * cleartext only for ".local", so a numeric address would be blocked by that
   * policy: a host that is not a resolvable ".local" name is a discovery fault
   * to fix, never a reason to widen the policy.
   */
  private fun resolveHost(serviceInfo: NsdServiceInfo): String {
    if (Build.VERSION.SDK_INT >= SERVICE_INFO_CALLBACK_SDK) {
      val hostname = normalizeHostname(serviceInfo.hostname)
      if (hostname.isNotEmpty()) {
        Log.d(NAME, "Resolved a Kanna desktop by its mDNS hostname.")
        return hostname
      }
    }
    val address = formatAddress(hostAddress(serviceInfo))
    if (address.isNotEmpty()) {
      // Shipped builds permit cleartext for ".local" only, so this desktop is
      // about to be unreachable. Say which half failed instead of leaving the
      // claim to fail silently.
      Log.w(NAME, "Resolved a Kanna desktop with no mDNS hostname.")
    }
    return address
  }

  private fun hostAddress(serviceInfo: NsdServiceInfo): InetAddress? {
    if (Build.VERSION.SDK_INT >= SERVICE_INFO_CALLBACK_SDK) {
      val addresses = serviceInfo.hostAddresses
      return addresses.firstOrNull { address -> address !is Inet6Address }
        ?: addresses.firstOrNull()
    }
    @Suppress("DEPRECATION")
    return serviceInfo.host
  }

  private fun normalizeHostname(rawHostname: String?): String {
    val hostname = rawHostname?.trim()?.trimEnd('.').orEmpty()
    if (hostname.isEmpty()) return ""
    return if (hostname.contains('.')) hostname else hostname + ".local"
  }

  private fun formatAddress(address: InetAddress?): String {
    val raw = address?.hostAddress?.substringBefore('%').orEmpty()
    if (raw.isEmpty()) return ""
    return if (address is Inet6Address) "[" + raw + "]" else raw
  }

  private fun emit(event: WritableMap) {
    val context = reactApplicationContext
    if (!context.hasActiveReactInstance()) return
    context.emitDeviceEvent(EVENT_NAME, event)
  }

  private fun onMain(browse: Int, body: () -> Unit) {
    mainHandler.post { if (browse == browseGeneration) body() }
  }

  companion object {
    const val NAME = "${ANDROID_MODULE_NAME}"
    private const val EVENT_NAME = "kannaBonjourServiceChanged"
    private const val DISCOVERY_SERVICE_TYPE = "${SERVICE_TYPE}"
    /** iOS reports the resolved type with its trailing dot; match it. */
    private const val EVENT_SERVICE_TYPE = "${SERVICE_TYPE}."
    private const val ERROR_CODE = "kanna_bonjour_unavailable"
    /** NsdManager.ServiceInfoCallback, and NsdServiceInfo.getHostname(). */
    private const val SERVICE_INFO_CALLBACK_SDK = 34
  }
}
`;
}

function androidPackageSource(packageName) {
  return `package ${packageName}

import com.facebook.react.ReactPackage
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.uimanager.ViewManager

/**
 * Generated by apps/mobile/plugins/withKannaBonjour.js. Edit the plugin, not
 * this file: prebuild overwrites it.
 */
class ${ANDROID_PACKAGE_CLASS} : ReactPackage {
  @Suppress("DEPRECATION")
  override fun createNativeModules(
    reactContext: ReactApplicationContext
  ): List<NativeModule> = listOf(${ANDROID_MODULE_NAME}(reactContext))

  override fun createViewManagers(
    reactContext: ReactApplicationContext
  ): List<ViewManager<in Nothing, in Nothing>> = emptyList()
}
`;
}

/**
 * Shipped Android identities deny cleartext by default, but pairing and every
 * authenticated LAN read/stream talk http/ws to a desktop on the local network.
 * Permit cleartext for mDNS names only — that is the route discovery actually
 * produces — instead of turning it on for every destination.
 */
const NETWORK_SECURITY_CONFIG_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by apps/mobile/plugins/withKannaBonjour.js -->
<network-security-config>
    <base-config cleartextTrafficPermitted="false" />
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">local</domain>
    </domain-config>
</network-security-config>
`;

function patchMainApplication(contents) {
  if (contents.includes(ANDROID_PACKAGE_CLASS)) {
    return contents;
  }

  // Expo's current template builds the package list with `.apply { }` and a
  // commented example add; older shapes return the list directly or name it.
  const applyBlock = contents.replace(
    /PackageList\(this\)\.packages\.apply \{/,
    `PackageList(this).packages.apply {\n          add(${ANDROID_PACKAGE_CLASS}())`
  );
  if (applyBlock !== contents) {
    return applyBlock;
  }

  const inlineReturn = contents.replace(
    /return PackageList\(this\)\.packages\b/,
    `return PackageList(this).packages.apply {\n            add(${ANDROID_PACKAGE_CLASS}())\n          }`
  );
  if (inlineReturn !== contents) {
    return inlineReturn;
  }

  const listReturn = contents.replace(
    /(val packages = PackageList\(this\)\.packages[\s\S]*?)(\n(\s*)return packages\b)/,
    `$1\n$3packages.add(${ANDROID_PACKAGE_CLASS}())$2`
  );
  if (listReturn !== contents) {
    return listReturn;
  }

  throw new Error(
    "Unsupported Expo MainApplication template; could not register Kanna's Bonjour module."
  );
}

function applyAndroidManifest(manifest) {
  const application = AndroidConfig.Manifest.getMainApplicationOrThrow(manifest);
  application.$["android:networkSecurityConfig"] = `@xml/${NETWORK_SECURITY_CONFIG_RESOURCE}`;
  return manifest;
}

function writeAndroidSources(projectRoot, packageName) {
  const sourceRoot = path.join(
    projectRoot,
    "android",
    "app",
    "src",
    "main",
    "java",
    ...packageName.split(".")
  );
  fs.mkdirSync(sourceRoot, { recursive: true });
  fs.writeFileSync(
    path.join(sourceRoot, `${ANDROID_MODULE_NAME}.kt`),
    androidModuleSource(packageName)
  );
  fs.writeFileSync(
    path.join(sourceRoot, `${ANDROID_PACKAGE_CLASS}.kt`),
    androidPackageSource(packageName)
  );
}

function writeNetworkSecurityConfig(projectRoot) {
  const xmlRoot = path.join(projectRoot, "android", "app", "src", "main", "res", "xml");
  fs.mkdirSync(xmlRoot, { recursive: true });
  fs.writeFileSync(
    path.join(xmlRoot, `${NETWORK_SECURITY_CONFIG_RESOURCE}.xml`),
    NETWORK_SECURITY_CONFIG_XML
  );
}

function patchAppDelegate(contents) {
  if (contents.includes("kannaMetroBundleURL()")) {
    return contents;
  }

  const patched = contents.replace(
    `  override func bundleURL() -> URL? {
#if DEBUG
    return RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: ".expo/.virtual-metro-entry")
#else
    return Bundle.main.url(forResource: "main", withExtension: "jsbundle")
#endif
  }`,
    `  override func bundleURL() -> URL? {
#if DEBUG
    return kannaMetroBundleURL()
#else
    return Bundle.main.url(forResource: "main", withExtension: "jsbundle")
#endif
  }

  private func kannaMetroBundleURL() -> URL? {
    let provider = RCTBundleURLProvider.sharedSettings()
    if provider.jsLocation == nil,
       let host = readBundledTextResource("ip"),
       !host.isEmpty {
      let port = readBundledTextResource("metro-port") ?? "8081"
      provider.jsLocation = "\\(host):\\(port)"
    }
    return provider.jsBundleURL(forBundleRoot: ".expo/.virtual-metro-entry")
  }

  private func readBundledTextResource(_ name: String) -> String? {
    guard let path = Bundle.main.path(forResource: name, ofType: "txt") else {
      return nil
    }
    return try? String(contentsOfFile: path, encoding: .utf8)
      .trimmingCharacters(in: .whitespacesAndNewlines)
  }`
  );
  if (patched === contents) {
    throw new Error("Unsupported Expo AppDelegate template; could not install Kanna's Metro endpoint.");
  }
  return patched;
}

function patchMetroPortScript(project) {
  const section = project.hash.project.objects.PBXShellScriptBuildPhase || {};
  for (const phase of Object.values(section)) {
    if (!phase || phase.name !== '"Bundle React Native code and images"') {
      continue;
    }
    const shellScript = phase.shellScript;
    if (typeof shellScript !== "string") {
      continue;
    }
    if (shellScript.includes("metro-port.txt")) {
      return;
    }
    const patched = shellScript.replace(
      "export PROJECT_ROOT=\\\"$PROJECT_DIR\\\"/..\\n\\n",
      "export PROJECT_ROOT=\\\"$PROJECT_DIR\\\"/..\\n\\nif [[ \\\"$CONFIGURATION\\\" = *Debug* && ! \\\"$PLATFORM_NAME\\\" == *simulator ]]; then\\n  mkdir -p \\\"$CONFIGURATION_BUILD_DIR/$UNLOCALIZED_RESOURCES_FOLDER_PATH\\\"\\n  echo \\\"${RCT_METRO_PORT:-8081}\\\" > \\\"$CONFIGURATION_BUILD_DIR/$UNLOCALIZED_RESOURCES_FOLDER_PATH/metro-port.txt\\\"\\nfi\\n\\n"
    );
    if (patched === shellScript) {
      break;
    }
    phase.shellScript = patched;
    return;
  }
  throw new Error(
    "Unsupported React Native bundle phase template; could not bundle Kanna's Metro port."
  );
}

function writeNativeSources(projectRoot) {
  const sourceRoot = IOSConfig.Paths.getSourceRoot(projectRoot);
  fs.mkdirSync(sourceRoot, { recursive: true });
  fs.writeFileSync(path.join(sourceRoot, "KannaBonjourModule.swift"), SWIFT_SOURCE);
  fs.writeFileSync(path.join(sourceRoot, "KannaBonjourModule.m"), OBJC_SOURCE);
}

function withKannaBonjour(config) {
  config = withKannaAndroidBonjour(config);

  config = withInfoPlist(config, (config) => {
    config.modResults = applyInfoPlist(config.modResults);
    return config;
  });

  config = withDangerousMod(config, [
    "ios",
    (config) => {
      writeNativeSources(config.modRequest.projectRoot);
      const appDelegatePath = IOSConfig.Paths.getAppDelegateFilePath(
        config.modRequest.projectRoot
      );
      fs.writeFileSync(
        appDelegatePath,
        patchAppDelegate(fs.readFileSync(appDelegatePath, "utf8"))
      );
      return config;
    }
  ]);

  return withXcodeProject(config, (config) => {
    const projectRoot = config.modRequest.projectRoot;
    const projectName = IOSConfig.XcodeUtils.getProjectName(projectRoot);
    IOSConfig.XcodeUtils.addBuildSourceFileToGroup({
      filepath: `${projectName}/KannaBonjourModule.swift`,
      groupName: projectName,
      project: config.modResults
    });
    IOSConfig.XcodeUtils.addBuildSourceFileToGroup({
      filepath: `${projectName}/KannaBonjourModule.m`,
      groupName: projectName,
      project: config.modResults
    });
    patchMetroPortScript(config.modResults);
    return config;
  });
}

function withKannaAndroidBonjour(config) {
  const packageName = config.android?.package;
  if (!packageName) {
    throw new Error("Kanna's Bonjour plugin needs android.package to generate its module.");
  }
  // A build that already permits cleartext everywhere (the dev identity, which
  // reaches a task-scoped server over the emulator host alias or an explicit
  // numeric URL) must keep that behavior: a network security config would
  // override `usesCleartextTraffic` and cut those hosts off.
  const scopedCleartext = config.android?.usesCleartextTraffic !== true;

  config = withDangerousMod(config, [
    "android",
    (config) => {
      writeAndroidSources(config.modRequest.projectRoot, packageName);
      if (scopedCleartext) {
        writeNetworkSecurityConfig(config.modRequest.projectRoot);
      }
      return config;
    }
  ]);

  config = withMainApplication(config, (config) => {
    config.modResults.contents = patchMainApplication(config.modResults.contents);
    return config;
  });

  if (!scopedCleartext) {
    return config;
  }

  return withAndroidManifest(config, (config) => {
    config.modResults = applyAndroidManifest(config.modResults);
    return config;
  });
}

module.exports = withKannaBonjour;
module.exports.__internal = {
  androidModuleSource,
  androidPackageSource,
  applyAndroidManifest,
  applyInfoPlist,
  NETWORK_SECURITY_CONFIG_XML,
  patchAppDelegate,
  patchMainApplication,
  patchMetroPortScript
};

function applyInfoPlist(plist) {
  const services = new Set(plist.NSBonjourServices || []);
  services.add(SERVICE_TYPE);

  return {
    ...plist,
    NSBonjourServices: Array.from(services),
    NSLocalNetworkUsageDescription: LOCAL_NETWORK_USAGE_DESCRIPTION
  };
}
