/**
 * Build the phone's design page and write it into the mobile app as a
 * generated module, the way apps/mobile ships its terminal assets:
 *
 *   pnpm --filter @kanna/design-editor build:phone
 *
 * The app loads it into a WebView from memory: nothing is fetched at
 * runtime, and the page reaches kanna-server only through the app's bridge.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { DESIGN_SCHEMA_VERSION } from "../src/schema";

const packageDir = join(dirname(fileURLToPath(import.meta.url)), "..");
execFileSync("npx", ["vite", "build", "--config", "vite.phone.config.ts"], { cwd: packageDir, stdio: "inherit" });
const dist = join(packageDir, "dist-phone");
const script = readFileSync(join(dist, "design-phone.js"), "utf8");
const cssFile = readdirSync(dist).find((name) => name.endsWith(".css"));
if (!cssFile) throw new Error("the phone build produced no stylesheet");
const css = readFileSync(join(dist, cssFile), "utf8");
const target = join(packageDir, "..", "..", "apps", "mobile", "src", "screens", "designEditorAssets.generated.ts");
writeFileSync(
  target,
  `// Generated by packages/design-editor/scripts/build-phone-assets.ts
// Do not edit by hand.

export const DESIGN_EDITOR_SCHEMA_VERSION = ${JSON.stringify(DESIGN_SCHEMA_VERSION)};
export const DESIGN_EDITOR_CSS = ${JSON.stringify(css)};
export const DESIGN_EDITOR_SCRIPT = ${JSON.stringify(script)};
`,
);
console.log(`wrote ${target} (${Math.round((script.length + css.length) / 1024)} KiB)`);
